"""empty message

Revision ID: 570068dde75e
Revises: 744066bb45a9
Create Date: 2024-07-28 10:40:57.174855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '570068dde75e'
down_revision = '744066bb45a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_planet')
    # ### end Alembic commands ###
