"""empty message

Revision ID: 744066bb45a9
Revises: 26bbbcf7ee7a
Create Date: 2024-07-28 10:12:53.883535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744066bb45a9'
down_revision = '26bbbcf7ee7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_people')
    # ### end Alembic commands ###
